---
configure_osx: yes

homebrew_installed_packages:
  - autoconf
  - gettext
  - libevent
  - sqlite
  - openssl
  - awscli
  - fzf
  - httpie
  - gh
  - jq
  - the_silver_searcher
  - tmux
  - wget
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - gpg
  - iperf
  - nmap
  - node
  - nvm
  - wrk
  - cowsay
  - git
  - lastpass-cli
  - pyenv
  - pyenv-virtualenv
  - pipenv
  - autojump
  - ansible

homebrew_uninstalled_packages: []

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - postman
  - zoomus
  - spotify
  - firefox
  - google-chrome
  - licecap
  - font-hack-nerd-font
  
homebrew_cask_uninstalled_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: "{{ lookup('lastpass', 'Apple Id', field='login') }}"
mas_password: "{{ lookup('lastpass', 'Apple Id') }}"
mas_upgrade_all_apps: true
mas_installed_apps:
  - { id: 425264550, name: "Blackmagic Disk Speed Test (3.0)" }
  - { id: 946399090, name: "org.telegram.desktop (2.4.2)" }
  - { id: 497799835, name: "com.apple.dt.Xcode (11.1)" }
  - { id: 425424353, name: "cx.c3.theunarchiver (4.2.2)" }
  - { id: 1003160018, name: "com.quip.Desktop (7.22.0)" }
  - { id: 803453959, name: "com.tinyspeck.slackmacgap (4.9.0)" }
  - { id: 1147396723, name: "desktop.WhatsApp (2.2039.9)" }
  - { id: 1518425043, name: "com.okatbest.boop (1.3.1)" }
  - { id: 926036361, name: "com.lastpass.LastPass (4.4.0)" }
  - { id: 707452888, name: "com.pingapp.app (3.0.9)" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

ohmyzsh_users:
  - user: "{{ ansible_user_id }}"     # user name
    theme: powerlevel10k/powerlevel10k  # ohmyzsh theme; use "random" for random theme
    ssh_ids: [id_rsa]                 # list of SSH ids to add to ohmyzsh ssh manager plugin
#    plugins: []                      # list of ohmyzsh plugins to install
    state: present                    # present or absent, to install/uninstall
    colorls: yes                      # Install colorls ruby gem

  - user: root
    theme: powerlevel10k/powerlevel10k
#    ssh_ids: []
#    plugins: []
    state: present
    colorls: no                       # Install colorls ruby gem

ohmyzsh_default_plugins:
  - git
  - autojump
  - aws
  - mvn
  - ssh-agent
  - tmux
  - history
  - python
  - pip
  - osx
  - brew

macos_terminal_colorscheme: "Solarized Dark (patched)"