roles:
  - name: drew-kun.nerdfonts 
  - name: drew-kun.terminus_powerline
  - name: geerlingguy.homebrew
  - name: caduri.ohmyzsh
  - name: geerlingguy.mas

collections:
  - name: git@github.com:ansible-collections/community.general.git
    type: git